### ISSUE TITLE
How do I generate this file, "text2cypher_batch_output.jsonl"?

### ISSUE THREAD

**Issue by ashokrs** [tomasonjo/text2cypher#1]
First I ran "generate_text2cypher_questions.ipynb" and it generated the following files:
text2cypher_questions.csv
text2cypher_schemas.csv
text2cypher_batch_input.jsonl

The "process_batch_output.ipynb" tries to read a file called "text2cypher_batch_output.jsonl".
This "text2cypher_batch_output.jsonl" is not available yet. How do I generate this file, "text2cypher_batch_output.jsonl"?

**Comment by tomasonjo** [comment]
https://platform.openai.com/docs/guides/batch

**Comment by ashokrs** [comment]
WoW! Tks. I know I am missing something...
I looked at the content of "text2cypher_batch_input.jsonl" and planning what to do... This link nails it.
Thanks again for your great work @tomasonjo
